version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/feedbackhub
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - feedbackhub-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=feedbackhub
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - feedbackhub-network

volumes:
  mongo_data:
    driver: local

networks:
  feedbackhub-network:
    driver: bridge 