version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      # Development environment configuration
      # Uses feedbackhub-local user → feedbackhub_local_db
      - NODE_ENV=development
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
      # Optional: Override with custom MongoDB URI if needed
      # - MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/database?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      # Mount source code for hot reloading
      - ../app:/app/app
      - ../lib:/app/lib
      - ../package.json:/app/package.json
      - ../package-lock.json:/app/package-lock.json
    restart: unless-stopped
    networks:
      - feedbackhub-network

networks:
  feedbackhub-network:
    driver: bridge 